name: Build image

on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string

env:
  BASE_REGISTRY_PATH: 147868451473.dkr.ecr.eu-west-1.amazonaws.com

jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Import Secrets
      uses: hashicorp/vault-action@v2.4.2
      with:
        url: https://vault.crispybacon.it
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          aws/creds/github-pipeline-access-role access_key | AWS_ACCESS_KEY_ID ;
          aws/creds/github-pipeline-access-role secret_key | AWS_SECRET_ACCESS_KEY ;
    - name: Wait for IAM credentials to be ready
      run: sleep 10
    - name: Create ECR registry
      run: aws ecr create-repository --repository-name ${{ env.PROJECT_NAME }} --region eu-west-1 || true
    - uses: actions/checkout@v3
    - name: Login ECR registry
      run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{ env.BASE_REGISTRY_PATH }}/${{ env.PROJECT_NAME }}
    - name: Build the Docker image
      run: docker build -t ${{ env.BASE_REGISTRY_PATH }}/${{ env.PROJECT_NAME }}:${{ github.sha }} .
    - name: Push docker image
      run: docker push ${{ env.BASE_REGISTRY_PATH }}/${{ env.PROJECT_NAME }}:${{ github.sha }}

