name: Build image

on:
  workflow_call:
    secrets:
      vault_token:
        required: true
      base_registry_path:
        required: true
    inputs:
      PROJECT_NAME:
        required: true
        type: string
      VAULT_AWS_NAME:
        required: false
        type: string
        default: aws_devops_tools
      REGISTRY_PATH:
        required: false
        type: string
        default: ${{ secrets.base_registry_path }}
    
jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Import Secrets
      uses: hashicorp/vault-action@v2.4.2
      with:
        url: https://vault.crispybacon.it
        token: ${{ secrets.vault_token }}
        secrets: |
          ${{ inputs.VAULT_AWS_NAME }}/creds/github-pipeline-access-role access_key | AWS_ACCESS_KEY_ID ;
          ${{ inputs.VAULT_AWS_NAME }}/creds/github-pipeline-access-role secret_key | AWS_SECRET_ACCESS_KEY ;
    - name: Wait for IAM credentials to be ready
      run: sleep 10
    - name: Create ECR registry
      run: aws ecr create-repository --repository-name ${{ inputs.PROJECT_NAME }} --region eu-west-1 || true
    - uses: actions/checkout@v3
    - name: Login ECR registry
      run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{ secrets.base_registry_path }}/${{ inputs.PROJECT_NAME }}
    - name: Build the Docker image
      run: docker build -t ${{ inputs.REGISTRY_PATH }}/${{ inputs.PROJECT_NAME }}:${{ github.sha }} .
    - name: Push docker image
      run: docker push ${{ inputs.REGISTRY_PATH }}/${{ inputs.PROJECT_NAME }}:${{ github.sha }}

