name: Rancher Deploy

on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string
      NAMESPACE: 
        required: true
        type: string
      DEPLOYMENT_NAME:
        required: true
        type: string
    secrets:
      base_registry_path:
        required: true

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy on Rancher
        run: |
          export IMAGE_TAG=${{ secrets.base_registry_path }}/${{ inputs.PROJECT_NAME }}:${{ github.sha }}
          echo "Deploying to Rancher..."
          curl -u "${{ secrets.RANCHER_TOKEN }}" \
          -X PATCH -H 'Content-Type: application/json-patch+json' \
          ${{ secrets.RANCHER_URL }}/k8s/clusters/c-pt57p/apis/apps/v1/namespaces/${{ inputs.NAMESPACE }}/deployments/${{ inputs.DEPLOYMENT_NAME }} \
          -d '[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "'$IMAGE_TAG'"}]'