name: Rancher Deploy

on:
  workflow_call:
    inputs:
      IMAGE_TO_DEPLOY:
        required: true
        type: string
      NAMESPACE: 
        required: true
        type: string
      DEPLOYMENT_NAME:
        required: true
        type: string
    secrets:
      rancher_token:
        required: true
      rancher_url:
        required: true

jobs:
  rancher:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy on Rancher
        run: |
          export IMAGE_TAG=${{ inputs.IMAGE_TO_DEPLOY }}
          echo "Deploying to Rancher..."
          curl -u "${{ secrets.rancher_token }}" \
          -X PATCH -H 'Content-Type: application/json-patch+json' \
          ${{ secrets.rancher_url }}/k8s/clusters/c-pt57p/apis/apps/v1/namespaces/${{ inputs.NAMESPACE }}/deployments/${{ inputs.DEPLOYMENT_NAME }} \
          -d '[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "'$IMAGE_TAG'"}]'
